## <b> Analyzing-and-Predicting-Calories-Burned </b>

### Data cleaning and preparation

##### Import the dataset and libraries

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [12]:
dataset_1 = pd.read_csv('calories.csv' , index_col=0)
dataset_2 = pd.read_csv('exercise.csv', index_col=0)

In [13]:
dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 14733363 to 11751526
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Calories  15000 non-null  float64
dtypes: float64(1)
memory usage: 234.4 KB


In [14]:
dataset_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 14733363 to 11751526
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Gender      15000 non-null  object 
 1   Age         15000 non-null  int64  
 2   Height      15000 non-null  float64
 3   Weight      15000 non-null  float64
 4   Duration    15000 non-null  float64
 5   Heart_Rate  15000 non-null  float64
 6   Body_Temp   15000 non-null  float64
dtypes: float64(5), int64(1), object(1)
memory usage: 937.5+ KB


In [15]:
dataset_2.head()

Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
User_ID                                                               
14733363    male   68   190.0    94.0      29.0       105.0       40.8
14861698  female   20   166.0    60.0      14.0        94.0       40.3
11179863    male   69   179.0    79.0       5.0        88.0       38.7
16180408  female   34   179.0    71.0      13.0       100.0       40.5
17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [16]:
dataset_1.head()

Calories
User_ID           
14733363     231.0
14861698      66.0
11179863      26.0
16180408      71.0
17771927      35.0

In [17]:
dataset = pd.concat([dataset_1, dataset_2], axis=1)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 14733363 to 11751526
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Calories    15000 non-null  float64
 1   Gender      15000 non-null  object 
 2   Age         15000 non-null  int64  
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.0+ MB


There is no missing values.

In [18]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

##### Encoding categorical data

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [23]:
print(X)

[[1 68 190.0 ... 29.0 105.0 40.8]
 [0 20 166.0 ... 14.0 94.0 40.3]
 [1 69 179.0 ... 5.0 88.0 38.7]
 ...
 [0 43 159.0 ... 16.0 90.0 40.1]
 [1 78 193.0 ... 2.0 84.0 38.3]
 [1 63 173.0 ... 18.0 92.0 40.5]]


#### Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

#### Feature Scaling

In [25]:
print(X[1,:])

[0 20 166.0 60.0 14.0 94.0 40.3]


In [26]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:,1:] = sc.fit_transform(X_train[:,1:])
X_test[:,1:] = sc.transform(X_test[:,1:])

### Exploratory data analysis